site_name: 'sample'
site_description: 'Main documentation for sample'
repo_url: https://github.com/jaysuzi5/sample
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'